### ISSUE TITLE
Linking fails on ArchLinux

### ISSUE THREAD

**Issue by woodgiraffe** [BlaXpirit/nim-csfml#3]
After installing it over nimble on ArchLinux, compiling it via "nim c example.nim" and then running it fails stating: "could not load: libcsfml-system.so".

The CSFML version on ArchLinux is "csfml 2.1-2" and locating it shows them installed correctly:

/usr/lib/libcsfml-system.so
/usr/lib/libcsfml-system.so.2
/usr/lib/libcsfml-system.so.2.1

**Comment by BlaXpirit** [comment]
CSFML itself is broken on Arch Linux. I've contacted the maintainer and they don't want to do anything about it.

From README.md:

> CSFML 2.1, which requires SFML **2.1**, must be installed to use it.

**Comment by woodgiraffe** [comment]
Thanks, I downgraded to SFML 2.1 in from the git-repo and it works fine now.
