### ISSUE TITLE
making types 'Drawable' and 'Transformable', in Nim way

### ISSUE THREAD

**Issue by hakanderyal** [BlaXpirit/nim-csfml#5]
Hey,

Thanks for great lib.

I'm new to Nim(and statically typed languages in general), and following along sfml tutorials for C++, converting examples to nim along the way.

In the tutorials, to make custom classes drawable and transformable, they inherit from drawable and transformable.

AFAIK there is no multiple inheritance in Nim, and couldn't find a definition for drawable in nim-csfml.

How can I achieve the same thing in Nim, with nim-csfml?

**Comment by BlaXpirit** [comment]
https://github.com/BlaXpirit/nim-csfml/tree/2.2/examples#snakes

**Comment by hakanderyal** [comment]
Everything makes much more sense now, thanks a lot!

**Comment by BlaXpirit** [comment]
#### Transformable:
- Add a [`Transformable`](http://blaxpirit.github.io/nim-csfml/csfml_graphics.html#Transformable) into your class (composition) and use it.

#### Putting them together:
- Inside `draw` apply [transform](blaxpirit.github.io/nim-csfml/csfml_graphics.html#transform,Transformable) to RenderStates
